# Generated by Django 3.1.3 on 2021-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deptartment',
            new_name='department',
        ),
    ]
