# Generated by Django 3.1.3 on 2021-02-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='date',
        ),
    ]
