# Generated by Django 3.1.3 on 2021-02-07 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0002_remove_tickets_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 7, 9, 11, 40, 148476, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
