# Generated by Django 3.1.3 on 2021-02-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0003_tickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_priority',
            field=models.CharField(choices=[('high_priority', 'high_priority'), ('normal_priority', 'normal_priority'), ('low_priority', 'low_priority ')], default='high_priority', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_status',
            field=models.CharField(choices=[('accomplished', 'تم الانجاز'), ('unaccomplished', 'لم يتم الانجاز')], default='unaccomplished', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('SW', 'software'), ('HW', 'hardware')], default='SW', max_length=2, null=True),
        ),
    ]
