# Generated by Django 3.1.3 on 2021-02-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0005_auto_20210203_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ticket_status',
            field=models.CharField(choices=[('مهمة جدا', 'مهمة جدا'), ('مهمة', 'مهمة'), ('متوسطة الاهمية', 'غير مهمة ')], default='مهمة جدا', max_length=14),
        ),
    ]
