# Generated by Django 3.1.3 on 2021-02-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticket', '0006_auto_20210204_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_priority',
            field=models.CharField(choices=[('مهمة جدا', 'مهمة جدا'), ('مهمة', 'مهمة'), ('متوسطة الاهمية', 'غير مهمة ')], default='مهمة جدا', max_length=14),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_status',
            field=models.CharField(choices=[('accomplished', 'تم الانجاز'), ('unaccomplished', 'لم يتم الانجاز')], default='unaccomplished', max_length=30),
        ),
    ]
